export { default as Header } from './Header/Header'
export { default as IntroSection } from './IntroSection/IntroSection'
export { default as MainSection } from './MainSection/MainSection'
export { default as Footer } from './Footer/Footer'
export { default as ProductSection } from './ProductSection/ProductSection'
export { default as CartSection } from './CartSection/CartSection'
export { default as CheckOut } from './CheckOut/CheckOut'